export const UPDATER_STATION_LIST = "UPDATER_STATION_LIST";
export const STATION_ERROR = "STATION_ERROR";
export const UPDATE_CURRENT_STATION = "UPDATE_CURRENT_STATION";
export const CURRENT_STATION = "CURRENT_STATION";
